### ISSUE TITLE
3 Is it possible to make this error copyable? 

### ISSUE THREAD

**Issue by hongwei1** [OpenBankProject/OBP-IntelliJ-plugin#1]
![image](https://user-images.githubusercontent.com/23308710/114171080-15525b00-9934-11eb-90c8-ff0eae843efc.png)

I prefer to copy this error and debug it.

**Comment by vladimirkozhaev** [comment]
Fixed with commit 258191667fc12d9a6932d54965eb792ae93058ec

**Comment by hongwei1** [comment]
![image](https://user-images.githubusercontent.com/23308710/114358267-03123000-9b73-11eb-8ee0-6b188d8d9e06.png)

**Comment by vladimirkozhaev** [comment]
Just rebuild the project

**Comment by vladimirkozhaev** [comment]
![New View Of The Problem](https://user-images.githubusercontent.com/1598180/114362619-31e2d300-9b80-11eb-8fd7-0713f3340c7c.jpg)
